import type { AuthoringCase } from "./authoring-cases.js";
const U = "id,username,name";
const G = "key,name,description";
const N = "id,role,state,current";
const R = "count,responsibility(name,description)";
const TOK = "name,creationTime,expirationTime";
const user = { id: 7, username: "example", name: "Example" };
const group = { key: "Developers", name: "Developers", description: "Synthetic" };
const role = { roleId: "PROJECT_DEVELOPER", scope: "p:Example" };
const roleArgs = ["PROJECT_DEVELOPER", "--project", "Example"];
const node = { id: "node1", role: "secondary_node", state: "online", current: false };
const responsibilities = {
  responsibility: [{ name: "CAN_PROCESS_BUILD_MESSAGES", description: "Messages" }],
};
const token = {
  name: "ExampleToken",
  creationTime: "20260830T100000+0000",
  expirationTime: "20991231T235959+0000",
};
const properties = (owner: "users" | "groups", path: string): AuthoringCase[] => [
  {
    argv: [owner, "properties", "list", "7"],
    method: "GET",
    path: path + "/properties",
    query: { fields: "count,property(name)" },
    response: { property: [{ name: "theme", value: "synthetic-hidden" }] },
    expected: ["theme"],
  },
  {
    argv: [owner, "properties", "exists", "7", "theme"],
    method: "GET",
    path: path + "/properties/theme",
    text: true,
    response: "synthetic-hidden",
    expected: { name: "theme", exists: true },
  },
  {
    argv: [owner, "properties", "set", "7", "theme", "dark"],
    method: "PUT",
    path: path + "/properties/theme",
    text: true,
    body: "dark",
    response: "dark",
    expected: { name: "theme", updated: true },
    permission: "Admin",
  },
  {
    argv: [owner, "properties", "delete", "7", "theme"],
    method: "DELETE",
    path: path + "/properties/theme",
    response: null,
    expected: { name: "theme", deleted: true },
    permission: "Admin",
  },
];
const roles = (owner: "users" | "groups", path: string): AuthoringCase[] => [
  {
    argv: [owner, "roles", "list", "7"],
    method: "GET",
    path: path + "/roles",
    response: { role: [role] },
    expected: [role],
  },
  {
    argv: [owner, "roles", "add", "7", ...roleArgs],
    method: "POST",
    path: path + "/roles",
    body: role,
    response: role,
    expected: role,
    permission: "Admin",
  },
  {
    argv: [
      owner,
      "roles",
      "replace",
      "7",
      "--item",
      '{"roleId":"PROJECT_DEVELOPER","project":"Example"}',
    ],
    method: "PUT",
    path: path + "/roles",
    body: { role: [role] },
    response: { role: [role] },
    expected: [role],
    permission: "Admin",
  },
  {
    argv: [owner, "roles", "show", "7", ...roleArgs],
    method: "GET",
    path: path + "/roles/PROJECT_DEVELOPER/p%3AExample",
    response: role,
    expected: role,
  },
  {
    argv: [owner, "roles", "grant", "7", ...roleArgs],
    method: owner === "users" ? "PUT" : "POST",
    path: path + "/roles/PROJECT_DEVELOPER/p%3AExample",
    response: role,
    expected: role,
    permission: "Admin",
  },
  {
    argv: [owner, "roles", "revoke", "7", ...roleArgs],
    method: "DELETE",
    path: path + "/roles/PROJECT_DEVELOPER/p%3AExample",
    response: null,
    expected: { ...role, revoked: true },
    permission: "Admin",
  },
];
export const adminCases: AuthoringCase[] = [
  {
    argv: ["users", "list"],
    method: "GET",
    path: "/users",
    query: { locator: "start:0,count:100", fields: `count,user(${U})` },
    response: { user: [user] },
    expected: [user],
  },
  {
    argv: ["users", "create", "example", "--name", "Example"],
    method: "POST",
    path: "/users",
    query: { fields: U },
    body: { username: "example", name: "Example" },
    response: user,
    expected: user,
    permission: "Admin",
  },
  {
    argv: ["users", "update", "7", "--name", "Example"],
    method: "PUT",
    path: "/users/id:7",
    query: { fields: U },
    body: { name: "Example" },
    response: user,
    expected: user,
    permission: "Admin",
  },
  {
    argv: ["users", "delete", "7"],
    method: "DELETE",
    path: "/users/id:7",
    response: null,
    expected: { userId: "7", deleted: true },
    permission: "Admin",
  },
  {
    argv: ["users", "sessions", "forget-remembered", "7"],
    method: "DELETE",
    path: "/users/id:7/debug/rememberMe",
    text: true,
    response: null,
    expected: { userId: "7", rememberedLoginsCleared: true },
    permission: "Admin",
  },
  {
    argv: ["users", "groups", "list", "7"],
    method: "GET",
    path: "/users/id:7/groups",
    query: { fields: `count,group(${G})` },
    response: { group: [group] },
    expected: [group],
  },
  {
    argv: ["users", "groups", "replace", "7", "--group", "Developers"],
    method: "PUT",
    path: "/users/id:7/groups",
    query: { fields: `count,group(${G})` },
    body: { group: [{ key: "Developers" }] },
    response: { group: [group] },
    expected: [group],
    permission: "Admin",
  },
  {
    argv: ["users", "groups", "show", "7", "Developers"],
    method: "GET",
    path: "/users/id:7/groups/key:Developers",
    query: { fields: G },
    response: group,
    expected: group,
  },
  {
    argv: ["users", "groups", "remove", "7", "Developers"],
    method: "DELETE",
    path: "/users/id:7/groups/key:Developers",
    response: null,
    expected: { userId: "7", group: "Developers", removed: true },
    permission: "Admin",
  },
  {
    argv: ["users", "sessions", "logout", "7"],
    method: "POST",
    path: "/users/id:7/logout",
    response: null,
    expected: { userId: "7", sessionsTerminated: true },
    permission: "Admin",
  },
  {
    argv: ["users", "permissions", "list", "7", "--project", "Example"],
    method: "GET",
    path: "/users/id:7/permissions",
    query: {
      locator: "project:(id:Example)",
      fields: "count,permissionAssignment(permission(id),project(id),isGlobalScope)",
    },
    response: {
      permissionAssignment: [
        { permission: { id: "VIEW_PROJECT" }, project: { id: "Example" }, isGlobalScope: false },
      ],
    },
    expected: [
      { permission: { id: "VIEW_PROJECT" }, project: { id: "Example" }, isGlobalScope: false },
    ],
  },
  ...properties("users", "/users/id:7"),
  ...roles("users", "/users/id:7"),
  {
    argv: ["users", "tokens", "list"],
    method: "GET",
    path: "/users/current/tokens",
    query: { fields: `count,token(${TOK})` },
    response: { token: [{ ...token, value: "synthetic-hidden" }] },
    expected: [token],
  },
  {
    argv: [
      "users",
      "tokens",
      "create",
      "ExampleToken",
      "--alias",
      "automation",
      "--expires",
      token.expirationTime,
      "--same-permissions",
    ],
    method: "POST",
    path: "/users/current/tokens",
    query: { fields: TOK + ",value" },
    body: { name: "ExampleToken", expirationTime: token.expirationTime },
    response: { ...token, value: "synthetic-issued-token" },
    expected: { ...token, alias: "automation", stored: true },
    permission: "Credentials",
  },
  {
    argv: ["users", "tokens", "delete", "ExampleToken"],
    method: "DELETE",
    path: "/users/current/tokens/ExampleToken",
    response: null,
    expected: { name: "ExampleToken", revoked: true },
    permission: "Credentials",
  },
  {
    argv: ["users", "fields", "get", "7", "username"],
    method: "GET",
    path: "/users/id:7/username",
    text: true,
    response: "example",
    expected: { userId: "7", field: "username", value: "example" },
  },
  {
    argv: ["users", "fields", "set", "7", "name", "Example"],
    method: "PUT",
    path: "/users/id:7/name",
    text: true,
    body: "Example",
    response: "Example",
    expected: { userId: "7", field: "name", updated: true },
    permission: "Admin",
  },
  {
    argv: ["users", "fields", "clear", "7", "name"],
    method: "DELETE",
    path: "/users/id:7/name",
    response: null,
    expected: { userId: "7", field: "name", cleared: true },
    permission: "Admin",
  },
  {
    argv: ["groups", "list"],
    method: "GET",
    path: "/userGroups",
    query: { fields: `count,group(${G})` },
    response: { group: [group] },
    expected: [group],
  },
  {
    argv: ["groups", "create", "Developers", "--name", "Developers", "--description", "Synthetic"],
    method: "POST",
    path: "/userGroups",
    query: { fields: G },
    body: group,
    response: group,
    expected: group,
    permission: "Admin",
  },
  {
    argv: ["groups", "show", "Developers"],
    method: "GET",
    path: "/userGroups/key:Developers",
    query: { fields: G },
    response: group,
    expected: group,
  },
  {
    argv: ["groups", "delete", "Developers"],
    method: "DELETE",
    path: "/userGroups/key:Developers",
    response: null,
    expected: { group: "Developers", deleted: true },
    permission: "Admin",
  },
  {
    argv: ["groups", "parents", "list", "7"],
    method: "GET",
    path: "/userGroups/key:7/parent-groups",
    query: { fields: `count,group(${G})` },
    response: { group: [group] },
    expected: [group],
  },
  {
    argv: ["groups", "parents", "replace", "7", "--group", "Developers"],
    method: "PUT",
    path: "/userGroups/key:7/parent-groups",
    query: { fields: `count,group(${G})` },
    body: { group: [{ key: "Developers" }] },
    response: { group: [group] },
    expected: [group],
    permission: "Admin",
  },
  ...properties("groups", "/userGroups/key:7"),
  ...roles("groups", "/userGroups/key:7"),
  {
    argv: ["server", "nodes", "list"],
    method: "GET",
    path: "/server/nodes",
    query: { fields: `count,node(${N})` },
    response: { node: [node] },
    expected: [node],
  },
  {
    argv: ["server", "nodes", "show", "node1"],
    method: "GET",
    path: "/server/nodes/id:node1",
    query: { fields: N },
    response: node,
    expected: node,
  },
  ...(["disabled", "effective", "enabled"] as const).map(
    (kind): AuthoringCase => ({
      argv: ["server", "nodes", "responsibilities", kind, "node1"],
      method: "GET",
      path: "/server/nodes/id:node1/" + kind + "Responsibilities",
      query: { fields: R },
      response: responsibilities,
      expected: responsibilities.responsibility,
    }),
  ),
  {
    argv: [
      "server",
      "nodes",
      "responsibilities",
      "set",
      "node1",
      "CAN_PROCESS_BUILD_MESSAGES",
      "false",
    ],
    method: "PUT",
    path: "/server/nodes/id:node1/enabledResponsibilities/CAN_PROCESS_BUILD_MESSAGES",
    text: true,
    jsonResponse: true,
    body: "false",
    response: responsibilities,
    expected: responsibilities.responsibility,
    permission: "Admin",
  },
  {
    argv: ["server", "api-version"],
    method: "GET",
    path: "/apiVersion",
    text: true,
    response: "2026.1",
    expected: { version: "2026.1" },
  },
];
