import type { AuthoringCase } from "./authoring-cases.js";
const CP = "id,name,cloudProviderId,project(id)";
const CI = "id,name,profile(id),agentPoolId,operatingSystemName";
const CN = "id,name,state,startDate,image(id),agent(id)";
const VR = "id,name,vcsName,project(id)";
const VI = "id,name,vcs-root-id,vcsName,modificationCheckInterval,commitHookMode";
const VC =
  "synchronizationMode,vcsRootId,format,buildSettingsMode,allowUIEditing,showSettingsChanges,storeSecureValuesOutsideVcs,portableDsl,settingsPath,applyChangesInDependenciesAndVcsSettings,dslExecutionMode";
const imageId = "profileId:Cloud,id:Image";
const instanceId = "profileId:Cloud,imageId:Image,id:Instance";
const imageLocator = "id:($base64:" + Buffer.from(imageId).toString("base64url") + ")";
const instanceLocator = "id:($base64:" + Buffer.from(instanceId).toString("base64url") + ")";
const cloudImage = { id: imageId, name: "Image", profile: { id: "Cloud" }, agentPoolId: 1 };
const instance = { id: instanceId, state: "running", image: { id: imageId }, agent: { id: 7 } };
const profile = {
  id: "Cloud",
  name: "Cloud",
  cloudProviderId: "example",
  project: { id: "Example" },
};
const root = { id: "Git", name: "Git", vcsName: "jetbrains.git", project: { id: "Example" } };
const vcsInstance = {
  id: "8",
  name: "Git",
  "vcs-root-id": "Git",
  vcsName: "jetbrains.git",
  modificationCheckInterval: 60,
  commitHookMode: false,
};
const rootPath = "/vcs-roots/id:Git";
const instancePath = "/vcs-root-instances/id:8";
const versionedPath = "/projects/id:Example/versionedSettings";
const config = {
  synchronizationMode: "enabled",
  vcsRootId: "Git",
  format: "kotlin",
  buildSettingsMode: "alwaysUseCurrent",
  allowUIEditing: true,
  showSettingsChanges: false,
  storeSecureValuesOutsideVcs: true,
  portableDsl: true,
};
const imageArgs = ["--cloud-profile", "Cloud", "--image", "Image"];
const instanceArgs = [...imageArgs, "--instance", "Instance"];
const state = { entry: [{ name: "main", value: "abc123" }] };
const scoped = (
  argv: string[],
  method: AuthoringCase["method"],
  path: string,
  query: Record<string, string>,
  response: unknown,
  expected: unknown,
  body?: unknown,
): AuthoringCase => ({
  argv,
  method,
  path,
  query,
  response,
  expected,
  ...(body === undefined ? {} : { body }),
});
export const infrastructureCases: AuthoringCase[] = [
  scoped(
    ["cloud", "images", "list"],
    "GET",
    "/cloud/images",
    { locator: "start:0,count:100", fields: `count,nextHref,cloudImage(${CI})` },
    { cloudImage: [cloudImage] },
    [cloudImage],
  ),
  scoped(
    ["cloud", "images", "show", ...imageArgs],
    "GET",
    "/cloud/images/" + imageLocator,
    { fields: CI },
    cloudImage,
    cloudImage,
  ),
  scoped(
    ["cloud", "instances", "list"],
    "GET",
    "/cloud/instances",
    { locator: "start:0,count:100", fields: `count,nextHref,cloudInstance(${CN})` },
    { cloudInstance: [instance] },
    [instance],
  ),
  scoped(
    ["cloud", "instances", "start", ...imageArgs],
    "POST",
    "/cloud/instances",
    {},
    null,
    { imageId, startRequested: true },
    { image: { id: imageId } },
  ),
  scoped(
    ["cloud", "instances", "show", ...instanceArgs],
    "GET",
    "/cloud/instances/" + instanceLocator,
    { fields: CN },
    instance,
    instance,
  ),
  scoped(
    ["cloud", "instances", "delete", ...instanceArgs, "--confirm"],
    "DELETE",
    "/cloud/instances/" + instanceLocator,
    {},
    null,
    { instanceId, forcedStopRequested: true },
  ),
  scoped(
    ["cloud", "instances", "force-stop", ...instanceArgs, "--confirm"],
    "POST",
    "/cloud/instances/" + instanceLocator + "/actions/forceStop",
    {},
    null,
    { instanceId, forcedStopRequested: true },
  ),
  scoped(
    ["cloud", "instances", "stop", ...instanceArgs],
    "POST",
    "/cloud/instances/" + instanceLocator + "/actions/stop",
    {},
    null,
    { instanceId, stopWhenFreeRequested: true },
  ),
  scoped(
    ["cloud", "profiles", "list"],
    "GET",
    "/cloud/profiles",
    { locator: "start:0,count:100", fields: `count,nextHref,cloudProfile(${CP})` },
    { cloudProfile: [profile] },
    [profile],
  ),
  scoped(
    ["cloud", "profiles", "show", "Cloud"],
    "GET",
    "/cloud/profiles/id:Cloud",
    { fields: CP },
    profile,
    profile,
  ),
  scoped(
    [
      "vcs",
      "roots",
      "create",
      "Git",
      "--name",
      "Git",
      "--project",
      "Example",
      "--url",
      "https://git.example.test/repository.git",
      "--branch",
      "refs/heads/main",
    ],
    "POST",
    "/vcs-roots",
    { fields: VR },
    root,
    root,
    {
      id: "Git",
      name: "Git",
      vcsName: "jetbrains.git",
      project: { id: "Example" },
      properties: {
        property: [
          { name: "authMethod", value: "ANONYMOUS" },
          { name: "branch", value: "refs/heads/main" },
          { name: "url", value: "https://git.example.test/repository.git" },
        ],
      },
    },
  ),
  scoped(["vcs", "roots", "delete", "Git"], "DELETE", rootPath, {}, null, {
    rootId: "Git",
    deleted: true,
  }),
  scoped(
    ["vcs", "roots", "instances", "Git"],
    "GET",
    rootPath + "/instances",
    { fields: `count,vcs-root-instance(${VI})` },
    { "vcs-root-instance": [vcsInstance] },
    [vcsInstance],
  ),
  scoped(
    ["vcs", "roots", "properties", "list", "Git"],
    "GET",
    rootPath + "/properties",
    { fields: "count,property(name)" },
    { property: [{ name: "branch", value: "synthetic-hidden" }] },
    ["branch"],
  ),
  scoped(
    ["vcs", "roots", "properties", "replace", "Git", "--property", "branch=refs/heads/main"],
    "PUT",
    rootPath + "/properties",
    { fields: "count,property(name)" },
    { property: [{ name: "branch", value: "synthetic-hidden" }] },
    ["branch"],
    { property: [{ name: "branch", value: "refs/heads/main" }] },
  ),
  scoped(
    ["vcs", "roots", "properties", "clear", "Git", "--confirm"],
    "DELETE",
    rootPath + "/properties",
    {},
    null,
    { rootId: "Git", cleared: true },
  ),
  {
    ...scoped(
      ["vcs", "roots", "properties", "exists", "Git", "branch"],
      "GET",
      rootPath + "/properties/branch",
      {},
      "synthetic-hidden",
      { name: "branch", exists: true },
    ),
    text: true,
  },
  {
    ...scoped(
      ["vcs", "roots", "properties", "set", "Git", "branch", "refs/heads/main"],
      "PUT",
      rootPath + "/properties/branch",
      {},
      "synthetic-hidden",
      { name: "branch", updated: true },
      "refs/heads/main",
    ),
    text: true,
  },
  scoped(
    ["vcs", "roots", "properties", "delete", "Git", "branch"],
    "DELETE",
    rootPath + "/properties/branch",
    {},
    null,
    { name: "branch", deleted: true },
  ),
  {
    ...scoped(
      ["vcs", "roots", "fields", "get", "Git", "vcsName"],
      "GET",
      rootPath + "/vcsName",
      {},
      "jetbrains.git",
      { rootId: "Git", field: "vcsName", value: "jetbrains.git" },
    ),
    text: true,
  },
  {
    ...scoped(
      ["vcs", "roots", "fields", "set", "Git", "name", "Renamed"],
      "PUT",
      rootPath + "/name",
      {},
      "Renamed",
      { rootId: "Git", field: "name", updated: true },
      "Renamed",
    ),
    text: true,
  },
  scoped(
    ["vcs", "instances", "list"],
    "GET",
    "/vcs-root-instances",
    { locator: "start:0,count:100", fields: `count,nextHref,vcs-root-instance(${VI})` },
    { "vcs-root-instance": [vcsInstance] },
    [vcsInstance],
  ),
  scoped(
    ["vcs", "instances", "check-changes", "8"],
    "POST",
    "/vcs-root-instances/checkingForChangesQueue",
    { locator: "id:8", requestor: "user", fields: `count,nextHref,vcs-root-instance(${VI})` },
    { "vcs-root-instance": [vcsInstance] },
    [vcsInstance],
  ),
  {
    ...scoped(
      ["vcs", "instances", "notify-commit", "8"],
      "POST",
      "/vcs-root-instances/commitHookNotification",
      { locator: "id:8", okOnNothingFound: "false" },
      "synthetic-hidden",
      { instanceId: "8", scheduled: true },
    ),
    text: true,
    responseStatus: 202,
  },
  scoped(
    ["vcs", "instances", "show", "8"],
    "GET",
    instancePath,
    { fields: VI },
    vcsInstance,
    vcsInstance,
  ),
  scoped(
    ["vcs", "instances", "properties", "8"],
    "GET",
    instancePath + "/properties",
    { fields: "count,property(name)" },
    { property: [{ name: "branch", value: "synthetic-hidden" }] },
    ["branch"],
  ),
  scoped(
    ["vcs", "instances", "state", "show", "8"],
    "GET",
    instancePath + "/repositoryState",
    { fields: "count,entry(name,value)" },
    state,
    state.entry,
  ),
  scoped(
    ["vcs", "instances", "state", "replace", "8", "--revision", "main=abc123"],
    "PUT",
    instancePath + "/repositoryState",
    { fields: "count,entry(name,value)" },
    state,
    state.entry,
    state,
  ),
  scoped(
    ["vcs", "instances", "state", "reset", "8", "--confirm"],
    "DELETE",
    instancePath + "/repositoryState",
    {},
    null,
    { instanceId: "8", stateReset: true },
  ),
  {
    ...scoped(
      ["vcs", "instances", "state", "created", "8"],
      "GET",
      instancePath + "/repositoryState/creationDate",
      {},
      "20260830T100000+0000",
      { instanceId: "8", creationDate: "20260830T100000+0000" },
    ),
    text: true,
  },
  {
    ...scoped(
      ["vcs", "instances", "fields", "get", "8", "commitHookMode"],
      "GET",
      instancePath + "/commitHookMode",
      {},
      "false",
      { instanceId: "8", field: "commitHookMode", value: "false" },
    ),
    text: true,
  },
  {
    ...scoped(
      ["vcs", "instances", "fields", "set", "8", "commitHookMode", "false"],
      "PUT",
      instancePath + "/commitHookMode",
      {},
      "false",
      { instanceId: "8", field: "commitHookMode", updated: true },
      "false",
    ),
    text: true,
  },
  scoped(
    ["vcs", "instances", "fields", "clear", "8", "lastVersionInternal"],
    "DELETE",
    instancePath + "/lastVersionInternal",
    {},
    null,
    { instanceId: "8", field: "lastVersionInternal", cleared: true },
  ),
  scoped(
    ["projects", "versioned-settings", "affected", "Example"],
    "GET",
    versionedPath + "/affectedProjects",
    { fields: "count,project(id,name)" },
    { project: [{ id: "Example", name: "Example" }] },
    [{ id: "Example", name: "Example" }],
  ),
  scoped(
    ["projects", "versioned-settings", "check-changes", "Example"],
    "POST",
    versionedPath + "/checkForChanges",
    {},
    null,
    { projectId: "Example", checkRequested: true },
  ),
  scoped(
    ["projects", "versioned-settings", "commit", "Example", "--confirm"],
    "POST",
    versionedPath + "/commitCurrentSettings",
    {},
    null,
    { projectId: "Example", commitRequested: true },
  ),
  scoped(
    ["projects", "versioned-settings", "config", "show", "Example"],
    "GET",
    versionedPath + "/config",
    { fields: VC },
    config,
    config,
  ),
  scoped(
    [
      "projects",
      "versioned-settings",
      "config",
      "replace",
      "Example",
      "--item",
      '{"synchronizationMode":"enabled","vcsRootId":"Git","format":"kotlin"}',
    ],
    "PUT",
    versionedPath + "/config",
    { fields: VC },
    config,
    config,
    config,
  ),
  scoped(
    ["projects", "versioned-settings", "config", "effective", "Example"],
    "GET",
    versionedPath + "/config/effective",
    { fields: `project(id),config(${VC})` },
    { project: { id: "Example" }, config },
    { project: { id: "Example" }, config },
  ),
  {
    ...scoped(
      ["projects", "versioned-settings", "config", "fields", "get", "Example", "format"],
      "GET",
      versionedPath + "/config/parameters/format",
      {},
      "kotlin",
      { projectId: "Example", field: "format", value: "kotlin" },
    ),
    text: true,
  },
  {
    ...scoped(
      [
        "projects",
        "versioned-settings",
        "config",
        "fields",
        "set",
        "Example",
        "showSettingsChanges",
        "true",
      ],
      "PUT",
      versionedPath + "/config/parameters/showSettingsChanges",
      {},
      "true",
      { projectId: "Example", field: "showSettingsChanges", updated: true },
      "true",
    ),
    text: true,
  },
  // Documented void success contract, not evidence that a current server can reset this field.
  scoped(
    [
      "projects",
      "versioned-settings",
      "config",
      "fields",
      "reset",
      "Example",
      "vcsRootId",
      "--confirm",
    ],
    "DELETE",
    versionedPath + "/config/parameters/vcsRootId",
    {},
    null,
    { projectId: "Example", field: "vcsRootId", resetRequested: true },
  ),
  scoped(
    ["projects", "versioned-settings", "context", "list", "Example"],
    "GET",
    versionedPath + "/contextParameters",
    {},
    {
      versionedSettingsContextParameter: [
        { name: "environment", value: "synthetic-hidden" },
        { name: "missing", value: null },
      ],
    },
    [
      { name: "environment", hasValue: true },
      { name: "missing", hasValue: false },
    ],
  ),
  scoped(
    [
      "projects",
      "versioned-settings",
      "context",
      "replace",
      "Example",
      "--property",
      "environment=uat",
    ],
    "PUT",
    versionedPath + "/contextParameters",
    {},
    { versionedSettingsContextParameter: [{ name: "environment", value: "synthetic-hidden" }] },
    [{ name: "environment", hasValue: true }],
    { versionedSettingsContextParameter: [{ name: "environment", value: "uat" }] },
  ),
  scoped(
    ["projects", "versioned-settings", "load", "Example", "--confirm"],
    "POST",
    versionedPath + "/loadSettings",
    { fields: "count,project(id,name)" },
    { project: [{ id: "Example", name: "Example" }] },
    [{ id: "Example", name: "Example" }],
  ),
  scoped(
    ["projects", "versioned-settings", "status", "Example"],
    "GET",
    versionedPath + "/status",
    { fields: "type,timestamp,dslOutdated,missingContextParameters" },
    { type: "info", dslOutdated: false, missingContextParameters: ["environment"] },
    { type: "info", dslOutdated: false, missingContextParameters: ["environment"] },
  ),
  scoped(
    ["projects", "versioned-settings", "tokens", "list", "Example", "--status", "used"],
    "GET",
    versionedPath + "/tokens",
    { status: "used" },
    { versionedSettingsToken: [{ name: "SecretId", value: "synthetic-hidden" }] },
    ["SecretId"],
  ),
  {
    ...scoped(
      [
        "projects",
        "versioned-settings",
        "tokens",
        "set",
        "Example",
        "--mapping",
        "SecretId=deployment",
      ],
      "POST",
      versionedPath + "/tokens",
      {},
      { versionedSettingsToken: [{ name: "SecretId" }] },
      { names: ["SecretId"], updated: true },
      { versionedSettingsToken: [{ name: "SecretId", value: "synthetic-input-secret" }] },
    ),
    permission: "Credentials",
    storedSecrets: { "input-secret:deployment": "synthetic-input-secret" },
  },
  {
    ...scoped(
      ["projects", "versioned-settings", "tokens", "delete", "Example", "--name", "SecretId"],
      "DELETE",
      versionedPath + "/tokens",
      {},
      { versionedSettingsToken: [] },
      { names: ["SecretId"], deleted: true },
      { versionedSettingsToken: [{ name: "SecretId" }] },
    ),
    permission: "Credentials",
  },
  {
    ...scoped(["server", "rest-version"], "GET", "/version", {}, "2026.1", { version: "2026.1" }),
    text: true,
  },
];
