import type { AuthoringCase } from "./authoring-cases.js";
export interface SystemCase extends AuthoringCase {
  accept?: string;
  responseMedia?: string;
  avatar?: boolean;
}
const dashboard = { id: "Release", name: "Release", project: { id: "Example" } };
const df = "id,name,project(id)";
const instance = { id: "Uat", currentState: "SUCCESSFUL", deploymentDashboard: { id: "Release" } };
const inf = "id,currentState,deploymentDashboard(id)";
const entry = { state: "SUCCESSFUL", deploymentDate: "20260830T120000+0000", build: { id: 7 } };
const role = {
  id: "release",
  name: "Release",
  permissions: { permission: [{ id: "VIEW_PROJECT" }] },
  included: { role: [] },
};
const rf = "id,name,permissions(permission(id)),included(role(id))";
const af = "id,timestamp,action(id,name)";
const hf = "identity,severity,healthCategory(id,name)";
const health = {
  identity: "example",
  severity: "WARN",
  healthCategory: { id: "unused", name: "Unused" },
};
const plugin = {
  name: "rest-api",
  displayName: "REST API",
  version: "2026.1",
  loaded: true,
  disabled: false,
};
const pf = "name,displayName,version,loaded,disabled";
const mute = {
  id: 9,
  scope: { project: { id: "Example" } },
  target: { tests: { test: [{ id: "3" }] } },
  resolution: { type: "manually" },
};
const mf =
  "id,scope(project(id),buildTypes(buildType(id))),target(tests(test(id)),problems(problem(id))),resolution(type,time)";
const lf =
  "valid,active,expired,obsolete,expirationDate,maintenanceEndDate,type,servers,agents,unlimitedAgents,buildTypes,unlimitedBuildTypes,pipelines,unlimitedPipelines";
const license = { valid: true, active: true, type: "enterprise", agents: 10 };
const licenseSecret = { "input-secret:license": "synthetic-license-value" };
const auth = {
  allowGuest: false,
  modules: { module: [{ name: "Default", properties: { property: [] } }] },
};
const safeAuth = { allowGuest: false, modules: [{ name: "Default" }] };
const cleanup = { enabled: false, maxCleanupDuration: 30, daily: { hour: 3, minute: 0 } };
export const systemCases: readonly SystemCase[] = [
  {
    method: "GET",
    path: "",
    argv: ["server", "rest-info"],
    text: true,
    response:
      "This is a root of TeamCity REST API.\nExplore what's inside from '/app/rest/server'.\nSee also notes on the usage at https://www.jetbrains.com/help/teamcity/rest/teamcity-rest-api-documentation.html",
    expected: { restPath: "/app/rest" },
  },
  {
    method: "POST",
    path: "/agentPools/id:2/authorizationTokens",
    argv: ["pools", "tokens", "create", "2", "--ttl", "300", "--store-as", "agent-one"],
    body: { timeToLiveSeconds: 300, count: 1 },
    response: { item: ["synthetic-agent-registration"] },
    expected: { poolId: 2, aliases: ["agent-one"], count: 1, timeToLiveSeconds: 300, stored: true },
    permission: "Credentials",
  },
  {
    method: "GET",
    path: "/audit",
    argv: ["audit", "list"],
    query: { locator: "start:0,count:100", fields: `count,auditEvent(${af})` },
    response: {
      count: 1,
      auditEvent: [
        {
          id: 4,
          timestamp: "20260830T120000+0000",
          action: { id: "CREATE", name: "Create" },
          comment: "omit",
        },
      ],
    },
    expected: {
      count: 1,
      items: [
        { id: 4, timestamp: "20260830T120000+0000", action: { id: "CREATE", name: "Create" } },
      ],
    },
  },
  {
    method: "GET",
    path: "/audit/id:4",
    argv: ["audit", "show", "4"],
    query: { fields: af },
    response: { id: 4, action: { id: "CREATE", name: "Create" } },
    expected: { id: 4, action: { id: "CREATE", name: "Create" } },
  },
  {
    method: "PUT",
    path: "/avatars/id:3",
    argv: ["users", "avatar", "replace", "3", "--file", "AVATAR_FILE"],
    avatar: true,
    response: null,
    expected: { userId: "3", replaced: true },
  },
  {
    method: "DELETE",
    path: "/avatars/id:3",
    argv: ["users", "avatar", "delete", "3"],
    response: null,
    expected: { userId: "3", deleted: true },
  },
  {
    method: "GET",
    path: "/buildTypes/id:Build/investigations",
    argv: ["jobs", "investigations", "Build"],
    query: {
      fields:
        "count,investigation(id,state,assignee(id),assignment(text,timestamp),scope(project(id),buildTypes(buildType(id))),target(anyProblem,tests(test(id)),problems(problem(id))),resolution(type,time))",
    },
    response: { count: 0 },
    expected: { count: 0, items: [] },
  },
  {
    method: "GET",
    path: "/buildTypes/id:Build/vcsRootInstances",
    argv: ["jobs", "vcs-instances", "Build"],
    query: {
      fields:
        "count,vcs-root-instance(id,name,vcs-root-id,vcsName,modificationCheckInterval,commitHookMode)",
    },
    response: { count: 1, "vcs-root-instance": [{ id: "8", name: "Git" }] },
    expected: { count: 1, items: [{ id: "8", name: "Git" }] },
  },
  {
    method: "GET",
    path: "/deploymentDashboards",
    argv: ["deployments", "list"],
    query: { locator: "start:0,count:100", fields: `count,deploymentDashboard(${df})` },
    response: { count: 1, deploymentDashboard: [dashboard] },
    expected: { count: 1, items: [dashboard] },
  },
  {
    method: "POST",
    path: "/deploymentDashboards",
    argv: ["deployments", "create", "Release", "--name", "Release", "--project", "Example"],
    body: dashboard,
    response: dashboard,
    expected: dashboard,
  },
  {
    method: "GET",
    path: "/deploymentDashboards/id:Release",
    argv: ["deployments", "show", "Release"],
    query: { fields: df },
    response: dashboard,
    expected: dashboard,
  },
  {
    method: "DELETE",
    path: "/deploymentDashboards/id:Release",
    argv: ["deployments", "delete", "Release", "--confirm"],
    response: null,
    expected: { id: "Release", deleted: true },
  },
  {
    method: "GET",
    path: "/deploymentDashboards/id:Release/instances",
    argv: ["deployments", "instances", "list", "Release"],
    query: { locator: "start:0,count:100", fields: `count,deploymentInstance(${inf})` },
    response: { count: 1, deploymentInstance: [instance] },
    expected: { count: 1, items: [instance] },
  },
  {
    method: "POST",
    path: "/deploymentDashboards/id:Release/instances",
    argv: [
      "deployments",
      "instances",
      "upsert",
      "Release",
      "Uat",
      "--state",
      "SUCCESSFUL",
      "--date",
      entry.deploymentDate,
      "--build",
      "7",
      "--confirm",
    ],
    body: { id: "Uat", attributes: {}, deploymentStateEntries: { deploymentStateEntry: [entry] } },
    response: instance,
    expected: instance,
  },
  {
    method: "GET",
    path: "/deploymentDashboards/id:Release/instances/id:Uat",
    argv: ["deployments", "instances", "show", "Release", "Uat"],
    query: { fields: inf },
    response: instance,
    expected: instance,
  },
  {
    method: "POST",
    path: "/deploymentDashboards/id:Release/instances/id:Uat",
    argv: [
      "deployments",
      "instances",
      "append-state",
      "Release",
      "Uat",
      "--state",
      "SUCCESSFUL",
      "--date",
      entry.deploymentDate,
      "--build",
      "7",
    ],
    body: entry,
    response: instance,
    expected: instance,
  },
  {
    method: "DELETE",
    path: "/deploymentDashboards/id:Release/instances/id:Uat",
    argv: ["deployments", "instances", "delete", "Release", "Uat", "--confirm"],
    response: null,
    expected: { dashboardId: "Release", instanceId: "Uat", deleted: true },
  },
  {
    method: "GET",
    path: "/health",
    argv: ["health", "list", "--global"],
    query: { locator: "global:true,start:0,count:100", fields: `count,healthItem(${hf})` },
    response: { count: 1, healthItem: [health] },
    expected: { count: 1, items: [health] },
  },
  {
    method: "GET",
    path: "/health/category",
    argv: ["health", "categories", "list"],
    query: { fields: "count,healthCategory(id,name)" },
    response: { count: 1, healthCategory: [{ id: "unused", name: "Unused" }] },
    expected: { count: 1, items: [{ id: "unused", name: "Unused" }] },
  },
  {
    method: "GET",
    path: "/health/category/id:unused",
    argv: ["health", "categories", "show", "unused"],
    query: { fields: "id,name" },
    response: { id: "unused", name: "Unused" },
    expected: { id: "unused", name: "Unused" },
  },
  {
    method: "GET",
    path: "/health/project:(id:Example),healthCategory:(id:unused)",
    argv: ["health", "show", "--project", "Example", "--category", "unused"],
    query: { fields: hf },
    response: health,
    expected: health,
  },
  {
    method: "GET",
    path: "/info",
    argv: ["server", "rest-plugin"],
    query: { fields: pf },
    accept: "application/xml",
    responseMedia: "application/xml",
    response:
      '<plugin name="rest-api" displayName="REST API" version="2026.1" loaded="true" disabled="false"/>',
    expected: plugin,
  },
  {
    method: "DELETE",
    path: "/mutes/multiple",
    argv: ["mutes", "delete-many", "--id", "9", "--confirm"],
    preflight: "/mutes/id:9",
    preflightFields: mf,
    preflightResponse: mute,
    body: { mute: [mute] },
    response: null,
    expected: { requestedIds: [9], serverAcknowledged: true, postconditionVerified: false },
  },
  {
    method: "GET",
    path: "/projects/id:Example/defaultValueSets",
    argv: ["projects", "default-value-sets", "Example"],
    query: { fields: "count,valueSet(name,displayName)" },
    response: { count: 1, valueSet: [{ name: "build", displayName: "Build", value: ["omit"] }] },
    expected: { count: 1, items: [{ name: "build", displayName: "Build" }] },
  },
  {
    method: "GET",
    path: "/projects/id:Example/deploymentDashboards",
    argv: ["projects", "deployments", "list", "Example"],
    query: { fields: `count,deploymentDashboard(${df})` },
    response: { count: 1, deploymentDashboard: [dashboard] },
    expected: { count: 1, items: [dashboard] },
  },
  {
    method: "GET",
    path: "/projects/id:Example/deploymentDashboards/id:Release",
    argv: ["projects", "deployments", "show", "Example", "Release"],
    query: { fields: df },
    response: dashboard,
    expected: dashboard,
  },
  {
    method: "GET",
    path: "/roles",
    argv: ["roles", "list"],
    query: { fields: `count,role(${rf})` },
    response: { count: 1, role: [role] },
    expected: { count: 1, items: [role] },
  },
  {
    method: "POST",
    path: "/roles",
    argv: ["roles", "create", "--name", "Release", "--permission", "VIEW_PROJECT"],
    query: { fields: rf },
    body: {
      name: "Release",
      permissions: { permission: [{ id: "VIEW_PROJECT" }] },
      included: { role: [] },
    },
    response: role,
    expected: role,
    permission: "Admin",
  },
  {
    method: "GET",
    path: "/roles/id:release",
    argv: ["roles", "show", "release"],
    query: { fields: rf },
    response: role,
    expected: role,
  },
  {
    method: "DELETE",
    path: "/roles/id:release",
    argv: ["roles", "delete", "release", "--confirm"],
    response: null,
    expected: { id: "release", deleted: true },
    permission: "Admin",
  },
  ...(["included", "permissions"] as const).flatMap((kind) =>
    (["PUT", "DELETE"] as const).map((method) => ({
      method,
      path: `/roles/id:release/${kind}/${kind === "included" ? "reader" : "VIEW_PROJECT"}`,
      argv: [
        "roles",
        kind,
        method === "PUT" ? "add" : "remove",
        "release",
        kind === "included" ? "reader" : "VIEW_PROJECT",
      ],
      query: { fields: rf },
      response: role,
      expected: role,
      permission: "Admin",
    })),
  ),
  {
    method: "GET",
    path: "/server/authSettings",
    argv: ["server", "authentication", "show"],
    response: auth,
    expected: safeAuth,
  },
  {
    method: "PUT",
    path: "/server/authSettings",
    argv: [
      "server",
      "authentication",
      "replace",
      "--item",
      JSON.stringify({ modules: [{ name: "Default" }], allowGuest: false }),
      "--confirm",
    ],
    body: auth,
    response: auth,
    expected: safeAuth,
    permission: "Admin",
  },
  {
    method: "GET",
    path: "/server/backup",
    argv: ["server", "backup", "status"],
    text: true,
    response: "Idle",
    expected: { progress: "Idle", completionVerified: false },
  },
  {
    method: "POST",
    path: "/server/backup",
    argv: ["server", "backup", "start", "example-backup", "--confirm"],
    query: {
      fileName: "example-backup",
      addTimestamp: "true",
      includeConfigs: "true",
      includeDatabase: "true",
      includeBuildLogs: "false",
      includePersonalChanges: "false",
      includeRunningBuilds: "false",
      includeSupplimentaryData: "false",
    },
    text: true,
    response: "example-backup.zip",
    expected: { fileName: "example-backup.zip", scheduled: true, completionVerified: false },
    permission: "Admin",
  },
  {
    method: "GET",
    path: "/server/cleanup",
    argv: ["server", "cleanup", "show"],
    response: cleanup,
    expected: cleanup,
  },
  {
    method: "PUT",
    path: "/server/cleanup",
    argv: ["server", "cleanup", "configure", "--item", '{"enabled":false}'],
    body: { enabled: false },
    response: cleanup,
    expected: cleanup,
    permission: "Admin",
  },
  {
    method: "GET",
    path: "/server/globalSettings",
    argv: ["server", "settings", "show"],
    response: { defaultQuietPeriod: 60, useEncryption: true, encryptionKey: "synthetic-omit" },
    expected: { defaultQuietPeriod: 60, useEncryption: true },
  },
  {
    method: "PUT",
    path: "/server/globalSettings",
    argv: ["server", "settings", "set", "--item", '{"maxArtifactSize":-1}'],
    body: { maxArtifactSize: -1 },
    response: { maxArtifactSize: -1 },
    expected: { maxArtifactSize: -1 },
    permission: "Admin",
  },
  {
    method: "GET",
    path: "/server/licensingData",
    argv: ["server", "licenses", "summary"],
    query: {
      fields: "serverLicenseType,maxAgents,unlimitedAgents,maxBuildTypes,unlimitedBuildTypes",
    },
    response: { serverLicenseType: "enterprise", maxAgents: 10 },
    expected: { serverLicenseType: "enterprise", maxAgents: 10 },
  },
  {
    method: "GET",
    path: "/server/licensingData/licenseKeys",
    argv: ["server", "licenses", "list"],
    query: { fields: `count,licenseKey(${lf})` },
    response: { count: 1, licenseKey: [license] },
    expected: { count: 1, items: [license] },
  },
  {
    method: "POST",
    path: "/server/licensingData/licenseKeys",
    argv: ["server", "licenses", "add", "--secret", "license"],
    query: { fields: `count,licenseKey(${lf})` },
    text: true,
    jsonResponse: true,
    body: "synthetic-license-value",
    storedSecrets: licenseSecret,
    response: { count: 1, licenseKey: [license] },
    expected: { count: 1, items: [license] },
    permission: "Admin",
  },
  {
    method: "GET",
    path: "/server/licensingData/licenseKeys/synthetic-license-value",
    argv: ["server", "licenses", "show", "license"],
    query: { fields: lf },
    storedSecrets: licenseSecret,
    response: license,
    expected: license,
  },
  {
    method: "DELETE",
    path: "/server/licensingData/licenseKeys/synthetic-license-value",
    argv: ["server", "licenses", "delete", "license", "--confirm"],
    storedSecrets: licenseSecret,
    response: null,
    expected: { alias: "license", deleted: true },
    permission: "Admin",
  },
  {
    method: "GET",
    path: "/server/metrics",
    argv: ["server", "metrics"],
    query: { fields: "count,metric(name,prometheusName,metricValues(metricValue(name,value)))" },
    response: {
      count: 1,
      metric: [
        {
          name: "queue",
          prometheusName: "queue",
          metricValues: { metricValue: [{ name: "size", value: 3, metricTags: ["omit"] }] },
        },
      ],
    },
    expected: {
      count: 1,
      items: [{ name: "queue", prometheusName: "queue", values: [{ name: "size", value: 3 }] }],
    },
  },
  {
    method: "GET",
    path: "/server/plugins",
    argv: ["server", "plugins"],
    query: { fields: `count,plugin(${pf})` },
    response: { count: 1, plugin: [plugin] },
    expected: { count: 1, items: [plugin] },
  },
  {
    method: "GET",
    path: "/server/version",
    argv: ["server", "field", "version"],
    text: true,
    response: "2026.1",
    expected: { field: "version", value: "2026.1" },
  },
];
